# Common Labels
labels:
  app: "dristi-case-pdf"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "dristi-case-pdf"


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_dristi_case_pdf"
  tag: v1.0.0-ee2012995905694a5cb0deeb46440e07d174d152
replicas: "1"


healthChecks:
  enabled: true
  livenessProbePath: "/dristi-case-pdf/"
  readinessProbePath: "/dristi-case-pdf/"
    
env: |
  - name: SERVER_PORT
    value: "8080"

