creation_rules:
  # upon creation of a file that matches the pattern *dev.yaml,
  # KMS set A is used
  # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
  - path_regex: charts/environments/env\-secrets\.yaml$
    pgp: 5248FCA6E9E9E41D211EBFCB98C64A75B4B4477D
#    kms: 'arn:aws:kms:ap-south-1:680148267093:key/b7cf18c6-4396-4aff-b391-783c8605180a'