# Common Labels
labels:
  app: "sunbirdrc-credential-service"
  group: "accelerator"

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "sunbirdrc-credential-service"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "sunbirdrc_credential_service_schema"
    image:
      repository: "sunbirdrc-credential-service-db"
      tag: sunbirdrc-mithun-028afe44b4-100

image:
  repository: "sunbirdrc-credential-service"
  tag: sunbirdrc-mithun-028afe44b4-100
replicas: "1"
healthChecks:
  enabled: false
  livenessProbePath: "/sunbirdrc-credential-service/health"
  readinessProbePath: "/sunbirdrc-credential-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx512m -Xms512m"
java-args: "-Dspring.profiles.active=monitoring"

env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SUNBIRD_CREDENTIAL_PATH
    value: /credentials/issue
  - name: SUNBIRD_CREDENTIAL_SCHEMA_PATH
    value: /credential-schema
  - name: SUNBIRD_TEMPLATE_PATH
    value: /template
  - name: SUNBIRD_QR_PATH
    value: /credentials/
  - name: SUNBIRD_REVOKE_PATH
    value: /credentials/
  - name: EGOV_MDMS_SEARCH_TENANT
    value: 
  - name: SUNBIRD_SAVE_VC_TOPIC
    value: save-vcid
  - name: SUNBIRD_UPDATE_VC_TOPIC
    value: update-vcid
  - name: EGOV_CREATE_VC_TOPIC
    value: create-vc
  - name: EGOV_RECREATE_VC_TOPIC
    value: recreate-vc
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH
    value: /egov-mdms-service/schema/v1/_search
  - name: EGOV_MDMS_CREATE
    value: /egov-mdms-service/schema/v1/_create
  - name: SUNBIRD_CREDENTIAL_SCHEMA_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: sunbird-credential-schema
  - name: SUNBIRD_CREDENTIAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: sunbird-credential-service
  - name: SURBIRD_REVOKE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
  
