# Common Labels
labels:
  app: "digit-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "digit-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/digit-ui"
  tag: v1.0.0-d36b8da32451d23f32f7b0a23f61d33797bd31fd
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/digit-ui/"
  readinessProbePath: "/digit-ui/"
    
extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-ui

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
