# Common Labels
labels:
  app: "digit-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "digit-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "digit-ui"
  tag: v1.0.0-45bde9d9faf15700ce2d060ca12b6973153ba70e
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/digit-ui/"
  readinessProbePath: "/digit-ui/"
    
extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-ui

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
