# Common Labels
labels:
  app: "digit-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "digit-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/digit-ui"
  tag: v1.0.0-e85be86aaca57f4544dcd25ee6524eea2cf93806
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/digit-ui/"
  readinessProbePath: "/digit-ui/"

env: |
  - name: REACT_APP_ESIGN_FILESTORE_ID
    valueFrom:
      configMapKeyRef:
        key: esign-filestore-id
        name: egov-config
    
extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-ui

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
