# Common Labels
labels:
  app: "icops-integration"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  # zuul: true
  context: "egov-kerala-icops"

initContainers:
  dbMigration:
    enabled: true
    schemaTable: "integration_service_schema"
    image:
      repository: "pucarsolutionsdev.azurecr.io/integration_db"
      tag: v1.0.0-96208de425988dcc2f65a25163c8b713b54eb8ac
# Container Configs
image:
   repository: "pucarsolutionsdev.azurecr.io/integration"
   tag: v1.0.0-96208de425988dcc2f65a25163c8b713b54eb8ac
replicas: "1"

env: |
  - name: JAVA_OPTS
    value: -Xmx128mi -Xms128mi
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: "SCHEMA_TABLE"
    value: "advocate_service_schema"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_FILE_STORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_SUMMONS_HOST
    valueFrom:
      configMapKeyRef:
        key: summons
        name: egov-service-host



