# Common Labels
labels:
  app: "icops-integration"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-kerala-icops"


# Container Configs
image:
   repository: "pucarsolutionsdev.azurecr.io/integration"
   tag: v1.0.0-c91fa291f9fc913bfb946f2e29eba69746777b0d
replicas: "1"



