# Common Labels
labels:
  app: "egov-indexer"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-indexer"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_indexer_schema"
    image:
      repository: "egov-indexer-db"
      tag: request-external-bug-fix-55924ec05b-63
  gitSync:
    enabled: true
    repo: "git@github.com:pucardotorg/dpg-configs"
    branch: "develop"

# Container Configs
image:
  repository: "egov-indexer"
  tag: request-external-bug-fix-55924ec05b-63
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-indexer/health"
  readinessProbePath: "/egov-indexer/health"
appType: "java-spring"
tracing-enabled: true
egov-indexer-yaml-repo-path: "file:///work-dir/dpg-configs/egov-indexer/witness-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/advocate-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/advocate-clerk-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/case-indexer.yml,file:///work-dir/dpg-configs/fsm/egov-indexer/egov-vehicle.yaml,file:///work-dir/dpg-configs/fsm/egov-indexer/egov-vendor.yaml,file:///work-dir/dpg-configs/fsm/egov-indexer/egov-fsm.yml,file:///work-dir/dpg-configs/egov-indexer/privacy-audit.yaml,file:///work-dir/dpg-configs/egov-indexer/collection-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/egov-telemetry-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/egov-uploader-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/error-queue.yml,file:///work-dir/dpg-configs/egov-indexer/finance-rolloutadotpion-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/payment-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/pgr-services.yml,file:///work-dir/dpg-configs/egov-indexer/rainmaker-pgr-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/rainmaker-pt-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/rainmaker-tl-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/chatbot-telemetry.yaml,file:///work-dir/dpg-configs/egov-indexer/chatbot-telemetry-v2.yaml,file:///work-dir/dpg-configs/egov-indexer/egov-vehicle.yaml,file:///work-dir/dpg-configs/egov-indexer/egov-vendor.yaml,file:///work-dir/dpg-configs/egov-indexer/egov-url-shortening-indexer.yaml,file:///work-dir/dpg-configs/egov-indexer/fire-noc-service.yml,file:///work-dir/dpg-configs/egov-indexer/egov-echallan.yml,file:///work-dir/dpg-configs/egov-indexer/egov-bpa-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/edcr-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/rainmaker-birth-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/rainmaker-death-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/egov-error-queue-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/citizen-feedback-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/egov-fsm.yml,file:///work-dir/dpg-configs/egov-indexer/fsm-inbox-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/contractservices-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/estimateservices-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/expensebill-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/individual-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/musterservices-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/organisationservices-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/individual-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/household-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/facility-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/measurement-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/ifms-pi-indexer.yml,file:///work-dir/dpg-configs/works/egov-indexer/expensepayment-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/egov-pqm-service.yml,file:///work-dir/dpg-configs/egov-indexer/pqm-service-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/pqm-anomaly-finder-indexer.yml,file:///work-dir/dpg-configs/egov-indexer/pgr-services.yml"
heap: "-Xmx192m -Xms192m"
indexer-host: "egov-indexer"

# Additional Container Envs
env: |
  - name: EGOV_SERVICES_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: {{ index .Values "indexer-host" }}
  - name: EGOV_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: es-indexer-host
  - name: EGOV_INDEXER_YML_REPO_PATH
    value: {{ index .Values "egov-indexer-yaml-repo-path" | quote }}
  {{- if index .Values "global" "serializers-timezone-in-ist" }}
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_STATELEVEL_TENANTID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_INDEXER_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: username
  - name: EGOV_INDEXER_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: password   