# Common Labels
labels:
  app: "egov-persister"
  group: "core"

# Init Containers Configs
initContainers:
  gitSync:
    enabled: true
    repo: "git@github.com:egovernments/configs"
    branch: "UAT"

# Container Configs
image:
  repository: "egov-persister"
  tag: core-2.9-lts-mvn-check-c33cfe45ab-7
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/common-persist/health"
  readinessProbePath: "/common-persist/health"
appType: "java-spring"
tracing-enabled: true
persist-yml-path: "file:///work-dir/kerala-configs/egov-persister/advocate-clerk-persister.yml,file:///work-dir/kerala-configs/egov-persister/advocate-persister.yml,file:///work-dir/kerala-configs/egov-persister/case-persister.yml"
heap: "-Xmx192m -Xms192m"
memory_limits: 512Mi
java-args: ""

# Additional Container Envs
env: |
  - name: EGOV_PERSIST_YML_REPO_PATH
    value: {{ index .Values "persist-yml-path" | quote }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAEGER_SAMPLER_PARAM
    value: "1"
