# Common Labels
labels:
  app: "audit-service"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "audit-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "audit_service_schema"
    image:
      repository: "audit-service-db"
      tag: core-2.9-lts-mvn-check-c33cfe45ab-9

# Container Configs
image:
  repository: "audit-service"
  tag: core-2.9-lts-mvn-check-c33cfe45ab-9
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/audit-service/health"
  readinessProbePath: "/audit-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx64m -Xms64m"
java-args: "-Dspring.profiles.active=monitoring"
memory_requests: 256Mi
persist-yml-path: https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/advocate-clerk-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/advocate-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/application-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/apportion-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/audit-service-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/billing-services-persist.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/boundary-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/case-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/egov-user-event-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/egov-workflow-v2-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/collection-migration-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/evidence-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/evidencewithoutworkflow-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/hearing-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/hrms-employee-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/individual-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/mdms-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/order-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/pg-service-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/pgr-migration-batch.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/pgr-services-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/pgr.v3.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/pgr.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/service-request-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/task-persister.yml,https://raw.githubusercontent.com/pucardotorg/dpg-configs/develop/egov-persister/witness-persister.yml
# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: audit-service
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: PROCESS_AUDIT_LOGS_KAFKA_TOPIC
    value: process-audit-records
  - name: PERSIST_AUDIT_LOGS_KAFKA_TOPIC
    value: persist-audit-records
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: EGOV_ENC_SIGN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: EGOV_PERSIST_YML_REPO_PATH
    value: {{ index .Values "persist-yml-path" | quote }}

