# Common Labels
labels:
  app: "e-sign"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "e-sign"


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/e-sign"
  tag: v1.0.0-e4c2a1988377009d99c7bd1f8d0e2187692f3bd9
replicas: "1"


healthChecks:
  enabled: true
  livenessProbePath: "/e-sign/"
  readinessProbePath: "/e-sign/"
    
env: |
  - name: SERVER_PORT
    value: "8080"

