# Common Labels
labels:
  app: "e-sign"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "e-sign"


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/e-sign"
  tag: v1.0.0-578a2038896cc8ca61db0a4188b9d4a4a9408c3a
replicas: "1"


healthChecks:
  enabled: true
  livenessProbePath: "/e-sign/"
  readinessProbePath: "/e-sign/"
    
env: |
  - name: SERVER_PORT
    value: "8080"

