# Common Labels
labels:
  app: "analytics"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "analytics"


# Init Containers Configs


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_analytics"
  tag: v1.0.0-b23ac4a5abdeeadaf8913e470e9b60e49086e520
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
memory_limits: 640Mi
env: |
  - name: JAVA_OPTS
    value: -Xmx256m -Xms256m
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /analytics
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_STATELEVEL_TENANTID
    value: "kl"
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        key: individual
        name: egov-service-host
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: KAFKA_TOPICS_CONSUMER
    value: save-wf-transitions
  - name: EGOV_INDEXER_ES_HOST_NAME
    valueFrom:
      configMapKeyRef:
        key: es-host
        name: egov-config
  - name: EGOV_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        key: es-indexer-host
        name: egov-config
  - name: EGOV_HEARING_HOST
    valueFrom:
      configMapKeyRef:
        key: hearing
        name: egov-service-host
  - name: EGOV_CASE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: EGOV_EVIDENCE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: evidence
  - name: EGOV_TASK_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: task
  - name: EGOV_APPLICATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: application
  - name: EGOV_ORDER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: order
  - name: EGOV_INDEXER_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: username
  - name: EGOV_INDEXER_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: password
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-mdms-service
        name: egov-service-host
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
