# Common Labels
labels:
  app: "kenlm"
  group: "backend"

# Ingress Configs
ingress:
#  zuul: true
  enabled: true
  context: "kenlm"


# Init Containers Configs


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/kenlm"
  tag: v1.0.0-dristi-experiment-1

replicas: "1"
httpPort: 8000
appType: "java-spring"
heap: "-Xmx64m -Xms64m"
java-args: "-Dspring.profiles.active=monitoring"

