# Common Labels
labels:
  app: "casenote"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "casenote"


# Init Containers Configs

# Container Configs
image:
  repository: "pucardev.azurecr.io/casenote"
  tag: v1.0.0-springbootnoteserver-fd283dc
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
heap: "-Xmx64m -Xms64m"
java-args: "-Dspring.profiles.active=monitoring"
memory_requests: 256Mi


env: |
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password

  
    
