# Common Labels
labels:
  app: "sbi-webpage"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
#  zuul: true
  context: "sbi-payments"


# Container Configs
image:
   repository: "pucarsolutionsdev.azurecr.io/sbi-ui"
   tag: v1.0.0-9b32798dc18d9fdbe1ab887e577c70a4caa4d6dd
replicas: "1"

env: |
  - name: EXTERNAL_HOST
    valueFrom:
      configMapKeyRef:
        key: sbi-url
        name: egov-service-host
  - name: DRISTI_URL
    valueFrom:
      configMapKeyRef:
        key: dristi-url
        name: egov-config
  - name: REDIRECT_URL
    valueFrom:
      configMapKeyRef:
        key: sbi-redirect-url
        name: egov-config




