# Common Labels
labels:
  app: "dristi-pdf"
  group: "rainmaker"

namespace: egov

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "egov-pdf"

# Init Containers Configs
#initContainers:
#  dbMigration:
#    enabled: true
#    schemaTable: "dristi_pdf_schema"
#    image:
#      repository: "dristi-pdf-db"

# Container Configs
image:
  repository: "pucardev.azurecr.io/dristi-pdf"
  tag: v1.0.0-88003db9a4c6d43dd132bac9281fb88036bcdd28
replicas: "1"

# Additional Container Envs
env: |
  - name: DB_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-host
  - name: DB_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: DB_PORT
    value: "5432"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_PDF_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: DRISTI_CASE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: DRISTI_ORDER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: order
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key:  egov-hrms
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key:  individual
  - name:  DRISTI_HEARING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hearing
  - name: EGOV_SUNBIRDRC_CREDENTIAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: sunbirdrc-credential-service
  - name: CONTEXT_PATH
    value: "/egov-pdf"    
  - name: EGOV_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name
