# Common Labels
labels:
  app: "etreasury"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "etreasury"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/etreasury"
  tag: v1.0.0-b6b9eec235bf9a706a966af50fa5a38b4b3f8ef6
healthChecks:
  enabled: true
  livenessProbePath: "/etreasury/"
  readinessProbePath: "/etreasury/"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id

