# Common Labels
labels:
  app: "e-sign-svc"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "e-sign-svc"


# Init Containers Configs


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_e-sign-svc"
  tag: v1.0.0-717112a67da76eaf008f8eba36a3c9aa2ab3a918
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
heap: "-Xmx64m -Xms64m"
java-args: "-Dspring.profiles.active=monitoring"
memory_requests: 256Mi




env: |
  
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: SERVER_PORT
    value: "8080"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore

    
