# Common Labels
labels:
  app: "e-sign-svc"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "e-sign-svc"


# Init Containers Configs

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_e-sign-svc"
  tag: v1.0.0-36e4cd719e16aedec416b518f48bf84b56e60389
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
heap: "-Xmx256m -Xms256m -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
java-args: "-Dspring.profiles.active=monitoring"
memory_limit: 512Mi
debugPort: 8000
remote_debug:
  enabled: true




env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: SERVER_PORT
    value: "8080"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: ESING_RESPONSE_URL
    valueFrom:
      configMapKeyRef:
        key: esign-interceptor
        name: egov-config
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"

    
