# Common Labels
labels:
  app: "epayments"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
#  zuul: true
  context: "epayments"


# Container Configs
image:
   repository: "pucarsolutionsdev.azurecr.io/epayments"
   tag: v1.0.0-0d454a1a68d5969c30b2edc72786a1c76bdb711a
replicas: "1"

env: |
  - name: EXTERNAL_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-services-fqdn-name
        name: egov-config
  - name: SERVER_URL
    valueFrom:
      configMapKeyRef:
        key: etreasury
        name: egov-config
  - name: DRISTI_URL
    valueFrom:
      configMapKeyRef:
        key: dristi-url
        name: egov-config




