# Common Labels
labels:
  app: "epayments"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "epayments"


# Container Configs
image:
   repository: "pucarsolutionsdev.azurecr.io/epayments"
   tag: latest
replicas: "1"



