# Common Labels
labels:
  app: "epayments"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
#  zuul: true
  context: "epayments"


# Container Configs
image:
   repository: "pucarsolutionsdev.azurecr.io/epayments"
   tag: v1.0.0-b6b9eec235bf9a706a966af50fa5a38b4b3f8ef6
replicas: "1"

env: |
  - name: SERVER_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-services-fqdn-name  



