name: Pucar-Install Workflow Solutions-QA

on:
  push:
    branches:
      - cronjob
  workflow_dispatch:
  schedule:
     - cron: '00 10 * * 1-5'
    # Run at 6:30 p.m. UTC (12 a.m. IST)
    # - cron: '30 18 * * 1-5'
    # Run at 2:30 a.m. UTC (8 a.m. IST)
   

jobs:
  stop-resources:
    # if: github.event_name == 'schedule' && github.event.schedule == '30 18 * * 1-5'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOLUTIONS_AZURE_CREDENTIALS }}

      # - name: Stop PostgreSQL Instance
      #   run: az postgres flexible-server stop --name pucar-solutions-qa-server --resource-group pucar-solutions-qa

      - name: Scale Down Node to 1
        run: |
           az aks nodepool scale \
            --resource-group pucar-solutions-qa \
            --cluster-name solutions-qa \
            --name default \
            --node-count 1

  start-resources:
    if: github.event_name == 'schedule' && github.event.schedule == '45 9 * * 1-5'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOLUTIONS_AZURE_CREDENTIALS }}

      # - name: Start PostgreSQL Instance
      #   run: az postgres flexible-server start --name pucar-solutions-qa-server --resource-group pucar-solutions-qa

      - name: Scale Up Node Pool to 4
        run: |
          az aks nodepool update \
            --resource-group pucar-solutions-qa \
            --cluster-name solutions-qa \
            --name default \
            --min-count 1 \
            --max-count 4 \
            --enable-cluster-autoscaler
