name: Cronjob Workflow Solutions-QA

on:
  schedule:
    - cron: '30 18 * * 1-5'
    - cron: '30 2 * * 1-5'
   

jobs:
  stop-resources:
    if: github.event_name == 'schedule' && github.event.schedule == '30 18 * * 1-5'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOLUTIONS_AZURE_CREDENTIALS }}

      - name: Stop PostgreSQL Instance
        run: az postgres flexible-server stop --name pucar-solutions-qa-server --resource-group pucar-solutions-qa
      - name: Scale Node Pool to 1
        run: |
          timeout 5m az aks nodepool scale \
            --resource-group pucar-solutions-qa \
            --cluster-name solutions-qa \
            --name default \
            --node-count 1
  start-resources:
    if: github.event_name == 'schedule' && github.event.schedule == '30 2 * * 1-5'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SOLUTIONS_AZURE_CREDENTIALS }}

      - name: Start PostgreSQL Instance
        run: az postgres flexible-server start --name pucar-solutions-qa-server --resource-group pucar-solutions-qa

      - name: Scale Up Node Pool to 4
        run: |
          timeout 5m az aks nodepool scale \
            --resource-group pucar-solutions-qa \
            --cluster-name solutions-qa \
            --name default \
            --node-count 4
